# Generated by Django 4.1.7 on 2023-05-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_model_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_model',
            name='users',
        ),
        migrations.AddField(
            model_name='project_model',
            name='users',
            field=models.ManyToManyField(to='api.user'),
        ),
    ]
