# Generated by Django 4.1.7 on 2023-05-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_project_model_users_project_model_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_users', to='api.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Project_model',
        ),
    ]
